# Generated by Django 3.1.3 on 2020-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='departements',
            name='libcom',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='libdep',
        ),
        migrations.AddField(
            model_name='departements',
            name='numdep',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regions',
            name='numreg',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
