# Generated by Django 3.1.3 on 2020-11-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_auto_20201104_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='codePostal',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communes',
            name='administrative_competence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='communes',
            name='information_access',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='communes',
            name='numeric_access',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='communes',
            name='numeric_competence',
            field=models.IntegerField(null=True),
        ),
    ]
