# Generated by Django 3.1.3 on 2020-11-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_auto_20201105_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communes',
            old_name='codePostal',
            new_name='code_postal',
        ),
    ]
