# Generated by Django 3.1.3 on 2020-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0007_auto_20201106_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='global_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
